### ISSUE TITLE
I have made all the settings as described in package but still on prerender.io I get {We haven't seen a request with your Prerender token yet.} and in body I get only <div class="root"></div>

### ISSUE THREAD

**Issue by nikhilgoswami** [meteor/galaxy-seo-package#10]
website https://www.siliconsofttech.com

**Comment by nikhilgoswami** [comment]
When I use `curl 'http://localhost:3000/https://siliconsofttech.com' `I am getting correct response 
with prerender running at localhost:3000, but when I use `curl -A Googlebot https://www.siliconsofttech.com`  get empty div like mentioned above I got no idea how to troubleshoot this.

My settings.json consitst 
`{ "PrerenderIO":
 {      
            "serviceUrl": "http://service.prerender.io/",
            "token": "token**********"
        }
}`

**Comment by iwoj** [comment]
I get the same problem, although I haven't tried running prerender locally.

**Comment by nikhilgoswami** [comment]
This was resolved after adding environment variables namely PRERENDERIO_TOKEN and PRERENDERIO_SERVICE_URL on meteor app.
