### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by Saeeed-B** [meteor/galaxy-seo-package#11]
@filipenevola @benjamn and others ...
I went through everything correctly, but the package does not work properly .

The steps I went through are as follows: 

1) The steps I went through are as follows  `meteor add mdg:seo`

2) And I downloaded this package  [prerender](https://github.com/prerender/prerender)

3) And this is the content of the server.js : 

![image](https://user-images.githubusercontent.com/36485982/102520661-29cec700-40a9-11eb-8d79-5d2fe300026c.png)

4) I ran this package on port 3033 

![image](https://user-images.githubusercontent.com/36485982/102520779-4cf97680-40a9-11eb-988a-218264191ea9.png)

5) And this is my meteor settings

![image](https://user-images.githubusercontent.com/36485982/102521166-d5781700-40a9-11eb-96ff-5d2245ead94d.png)

The problem is that nothing works properly, meaning the content is not rendered

Content should now be at the address below, but it is not

`view-source:http://localhost:3000/?_escaped_fragment_=`

![image](https://user-images.githubusercontent.com/36485982/102521403-238d1a80-40aa-11eb-852d-8eba0d16be34.png)

And when I try the following curl, it does not work and does not return the correct content: 

`curl -A Googlebot http://localhost:3000`

![image](https://user-images.githubusercontent.com/36485982/102522703-d742da00-40ab-11eb-950d-0fb84f741d3e.png)
As you can see, the content of the div App is empty

But when I try the following curl, it works properly and returns the correct content : 

`curl http://localhost:3033/render?url=http://localhost:3000/
`

**Comment by Saeeed-B** [comment]
Exactly the problem was found.
The problem was that I did not set the token.
I think this package has a logical flaw, because the prerender server can have no tokens.
And can be without authentication.
On the other hand, in addition to having tokens, it can also have a username. Which is not included in the package

**Comment by filipenevola** [comment]
Do you mean the configuration for non-Galaxy users is incorrect?

What are the necessary changes? Could you make a PR?

**Comment by filipenevola** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while.
