### ISSUE TITLE
Does this actually work with Google?

### ISSUE THREAD

**Issue by csillag** [meteor/galaxy-seo-package#2]
The [blog post announcing this feature](http://info.meteor.com/blog/seo-automatic-prerendering-meteor-app) says this:

> Galaxy will automatically pass requests from search engine and social network crawlers (e.g. Google, Bing, Facebook, Twitter, etc.) to the prerender.io service, which then 

My question is: is it Galaxy that does this, outside of my application, or is it simply [the `shouldShowPrerenderedPage` function](https://github.com/prerender/prerender-node/blob/10e8a385086563d10e25f01346a97c5ffb203766/index.js#L122) in the [dfischer:prerenderio](https://atmospherejs.com/dfischer/prerenderio) meteor package?

In any case, according to my testing (with Google's "Fetch as Google" tool), this no longer works, since Google won't send the required `_escaped_fragment_` query param any more, and the user agent is not explicitly recognized either.

I already opened an issue about this at the prerender package (https://github.com/prerender/prerender-node/issues/105), but based on Galaxy's (sparse) relevant documentation, I am not sure that Galaxy is relying on the decision of that function, that's why I am bringing this up here, too.

**Comment by csillag** [comment]
Update: it turns out that GoogleBot in fact works as expected; it's only Google's "Fetch as Google" tool that misbehaves. In other works, there is no real bug, only the test tool is broken. Therefore, I am closing the issue.

**Comment by maxenceC** [comment]
> it's only Google's "Fetch as Google" tool that misbehaves

Can confirm,  dfischer:prerenderio and prerender-node works properly, Fetch as Google appear to be broken, at least for this use case

thanks @csillag
