### ISSUE TITLE
Whitelist/Blacklist? 

### ISSUE THREAD

**Issue by markudevelop** [meteor/galaxy-seo-package#4]
Is that working and how?

I tried the following with settings.json but can't really know for sure:

```
  "PrerenderIO": {
    "blacklisted": "/search"
  }
```

Thanks!

**Comment by markudevelop** [comment]
Still have issues with this I want to avoid weird hacks to avoid this, how do we pass settings to prerender?

**Comment by derwaldgeist** [comment]
Can't believe that this important question is still open since 2016?

**Comment by derwaldgeist** [comment]
Ok, I just copied the code from `server.js` and adapted it to my needs. Works.

**Comment by filipenevola** [comment]
Hi @derwaldgeist as you can see this is indeed a very old issue.

What were the changes that you have to do in your case? Was it around blacklist / whitelist? Do you think is worth a PR?

Thanks.

**Comment by filipenevola** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while.
