### ISSUE TITLE
compatbile with user-agents?

### ISSUE THREAD

**Issue by bgadrian** [meteor/galaxy-seo-package#8]
Hello,

The prerender works as documented, with the _fragment_ parameter, but the prerender plugin works based on user-agents too.

https://github.com/prerender/prerender-node/blob/master/index.js#L37

My problem is that on my meteor map, it doesn't work only using the user-agent
`curl --user-agent "Googlebot/2.1 (+http://www.google.com/bot.html)" https://mywebsite` , it is a limitation/incompatibility of the WebApp.rawConnectHandlers? I think the original plugin is made for express. 

Thanks.

**Comment by zmikaya** [comment]
The issue is documented at [https://prerender.io/documentation/google-support](https://prerender.io/documentation/google-support). It appears that this summer, Google has stopped using the "?_escaped_fragment_=" protocol. This package needs a pull request or a minor update to fix the issue.

**Comment by bgadrian** [comment]
I think this project uses the prerender-node 3.2.0 version which already has the 'googlebot' added onto the list, so it should be safe! I'm using an older version so I think this is the cause of the problem.

Thanks!

**Comment by zmikaya** [comment]
Now that I look more carefully, you're exactly correct.

**Comment by bgadrian** [comment]
Sorry for the issue, my problem was the prerender-node version, and It was installed directly from node not trough the galaxy packages.
